<?php

########################################################################
# Extension Manager/Repository config file for ext: "community"
#
# Auto generated by Extbase Kickstarter 2010-05-28
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Community',
	'description' => 'A flexible community system based on Extbase and Fluid',
	'category' => 'plugin',
	'author' => 'Pascal Jungblut',
	'author_email' => 'mail@pascal-jungblut.com',
	'author_company' => '',
	'shy' => '',
	'dependencies' => 'cms,extbase,fluid,enetcache,comments',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => 0,
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.6.0',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
			'comments' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>